package com.experis.de.MeFit.models;


import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "GoalWorkout")
@Schema(description = "GoalWorkout Model")
public @Data class GoalWorkout {

    //autogenerated ID which never has to be defined in future functions.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @OneToOne
    @JoinColumn(name = "workout_id")
    private Workout workout;

    @OneToOne
    @JoinColumn(name = "goal_id")
    private Goal goal;

    private boolean completed;

}
