package com.experis.de.MeFit.models;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;

@Entity
@DynamicUpdate
@Table(name = "Login")
@Schema(description = "User Model")
public @Data class User {

    //autogenerated ID which never has to be defined in future functions.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    //Here the static components of the model
    @Column(name="firstName", nullable = false)
    private String firstName;

    @Column(name="lastName", nullable = false)
    private String lastName;

    @Column(name="email", nullable = false)
    private String email;

    @OneToOne
    @JoinColumn(name = "profile_id", referencedColumnName = "id")
    private Profile profile;

    /*
    @JsonGetter("profile")
    public String userGetter() {
        if (profile != null)
            return "/api/v1/profiles/" + profile.getId();
        else
            return null;
    }
    */

    /*
    @Column(name="password",
            nullable = false,
            columnDefinition = "TEXT")
    private String password;

    //related data
    //user - role - relation
    @OneToMany
    @JoinColumn(name = "user_id")
    private Set<Role> roles = new HashSet<>();

    // restricts the output to a List of IDs of the movies
    @JsonGetter("roles")
    public List<String> roles() {
        if(roles != null) {
            return roles.stream()
                    .map(role -> {
                        return "/api/v1/roles/" + role.getId();
                    }).collect(Collectors.toList());
        }
        return null;
    }
    */

}
