package com.experis.de.MeFit.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

@Entity
@DynamicUpdate
@Table(name = "Workout")
@Schema(description = "Workout Model")
public @Getter
    @Setter
    @RequiredArgsConstructor
    class Workout {

    //autogenerated ID which never has to be defined in future functions.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    //Here the static components of the model
    @Column(nullable = false, length = 100)
    private String name;

    @Column(name="type",
            nullable = false,
            columnDefinition = "TEXT")
    private String type;

    //related data
    //programs - workouts -binding
    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.DETACH})
    @JoinTable(
            name="workout_programs",
            joinColumns = {@JoinColumn(name="workout_id")},
            inverseJoinColumns = {@JoinColumn(name="program_id")}
    )
    private Set<Program> programs = new HashSet<>();

    //to regulate the output only a List of the programIDs will be returned
    @JsonGetter("programs")
    public List<String> programsGetter() {
        if(programs != null){
            return programs.stream()
                    .map(program -> {
                        return "/api/v1/programs/" + program.getId();
                    }).collect(Collectors.toList());
        }
        return null;
    }

    //exercises - workouts - relation
    @ManyToMany(cascade = {/*CascadeType.ALL, */CascadeType.PERSIST, CascadeType.MERGE, CascadeType.DETACH}, mappedBy = "workouts")
    public Set<Exercise> exercises= new HashSet<>();

    //restricts the output to a List of character IDs
    @JsonGetter("exercises")
    public List<String> exercises() {
        return exercises.stream()
                .map(exercise -> {
                    return "/api/v1/exercises/" + exercise.getId();
                }).collect(Collectors.toList());
    }

    //related data
    //workout - goal - relation
    @ManyToOne(cascade = {/*CascadeType.ALL, */CascadeType.PERSIST, CascadeType.MERGE, CascadeType.DETACH})
    @JoinColumn(name="goal_id")
    private Goal goal;

    //restricts the output to the muscle group ID
    @JsonGetter("goal")
    public String goal() {
        if(goal != null){
            return "/api/v1/goals/" + goal.getId();
        }else{
            return null;
        }
    }

}
